version: "3.9"
services: 
    python:
        image: auth
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: auth
        volumes: 
            - ./src/:/auth/src/
            # - ./data/:/auth/data/
        tty: true