version: "3.9"
services: 
    python:
        image: python:3.9.5-slim-buster
        container_name: auth_python
        volumes: 
            - ./python/:/auth_app/
            - ./sqlite3/data/:/data/
        tty: true
    sqlite3:
        image: auth_sqlite3
        build: 
            context: ./sqlite3
            dockerfile: Dockerfile
        container_name: auth_sqlite3
        volumes: 
            - ./sqlite3/data/:/data/